apiVersion: v1
kind: Secret
metadata:
  name: book-mariadb
  namespace: default
  labels:
    app: book-mariadb
type: Opaque
data:
  mariadb-root-password: OWI3NTI2YzY1YjJhZGExMTkzZDZjZmFlOWQxYTliMDIxYTQwMmYyYjE0YjFkM2IyNmZjZjVmZWVlN2Yw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-mariadb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-mariadb
  template:
    metadata:
      labels:
        app: book-mariadb
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: mariadb
          image: mariadb:10.5.3
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: book-mariadb
                  key: mariadb-root-password
            - name: MYSQL_DATABASE
              value: book
          #        command:
          #        - mysqld
          #        - --lower_case_table_names=1
          #        - --skip-ssl
          #        - --character_set_server=utf8mb4
          #        - --explicit_defaults_for_timestamp
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql/
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: book-mariadb
  namespace: default
spec:
  selector:
    app: book-mariadb
  ports:
    - port: 3306
